"""Validate raw data sources before preprocessing.

This script checks raw source readiness before processed datasets are built.
It does not run preprocessing, model training, calibration, or simulation.

Generated outputs:
- reports/source_validation.csv
- reports/source_validation.md
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[2]
RAW_DIR = PROJECT_ROOT / "data" / "raw"
REPORTS_DIR = PROJECT_ROOT / "reports"
MANIFEST_PATH = RAW_DIR / "source_manifest.csv"
SOURCE_VALIDATION_CSV_PATH = REPORTS_DIR / "source_validation.csv"
SOURCE_VALIDATION_MD_PATH = REPORTS_DIR / "source_validation.md"

REQUIRED_COLUMNS = {
    "raw_file_name",
    "dataset_name",
    "expected_columns",
    "verification_status",
}

RESULT_COLUMNS = ["raw_file_name", "check_name", "status", "detail"]


def parse_expected_columns(value: object) -> list[str]:
    """Parse semicolon-separated expected column names from the manifest."""
    return [column.strip() for column in str(value).split(";") if column.strip()]


def add_result(
    results: list[dict[str, Any]],
    raw_file_name: str,
    check_name: str,
    passed: bool,
    detail: str,
) -> None:
    """Append a PASS/FAIL validation result."""
    status = "PASS" if passed else "FAIL"
    results.append(
        {
            "raw_file_name": raw_file_name,
            "check_name": check_name,
            "status": status,
            "detail": detail,
        }
    )
    print(f"{status} {check_name}: {raw_file_name}: {detail}")


def format_markdown_table(headers: list[str], rows: list[list[Any]]) -> str:
    """Return a small Markdown table without extra dependencies."""
    header_row = "| " + " | ".join(headers) + " |"
    separator_row = "| " + " | ".join("---" for _ in headers) + " |"
    data_rows = ["| " + " | ".join(str(value) for value in row) + " |" for row in rows]
    return "\n".join([header_row, separator_row, *data_rows])


def write_reports(results: list[dict[str, Any]]) -> None:
    """Write source validation results to CSV and Markdown files."""
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    results_df = pd.DataFrame(results, columns=RESULT_COLUMNS)
    results_df.to_csv(SOURCE_VALIDATION_CSV_PATH, index=False)

    failed_count = int((results_df["status"] == "FAIL").sum())
    passed_count = int((results_df["status"] == "PASS").sum())
    summary_rows = [
        ["Total checks", len(results_df)],
        ["Passed checks", passed_count],
        ["Failed checks", failed_count],
    ]

    sections = [
        "# Source Validation Report",
        "",
        "This file is generated by `python src/data/validate_sources.py`.",
        "It should be reviewed before preprocessing, model training, calibration, or tournament simulation.",
        "",
        "## Run Summary",
        "",
        f"- Run timestamp: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
        "",
        format_markdown_table(["Metric", "Value"], summary_rows),
        "",
        "## Detailed Checks",
        "",
        format_markdown_table(["Raw File", "Check", "Status", "Detail"], results_df.values.tolist()),
        "",
    ]

    if failed_count:
        sections.extend(
            [
                "## Required Action if Failed",
                "",
                "One or more source validation checks failed. Fix the raw file path, raw CSV content, or `data/raw/source_manifest.csv` before running preprocessing.",
                "",
                "Do not continue to preprocessing while source validation fails.",
                "",
            ]
        )
    else:
        sections.extend(["## Result", "", "Source validation passed.", ""])

    SOURCE_VALIDATION_MD_PATH.write_text("\n".join(sections), encoding="utf-8")
    print(f"Saved source validation CSV to: {SOURCE_VALIDATION_CSV_PATH}")
    print(f"Saved source validation report to: {SOURCE_VALIDATION_MD_PATH}")


def validate_sources() -> list[dict[str, Any]]:
    """Run source validation checks and return result rows."""
    results: list[dict[str, Any]] = []

    if not MANIFEST_PATH.exists():
        add_result(
            results,
            "source_manifest.csv",
            "manifest_exists",
            False,
            f"Manifest not found: {MANIFEST_PATH}",
        )
        write_reports(results)
        return results

    add_result(
        results,
        "source_manifest.csv",
        "manifest_exists",
        True,
        f"Found manifest: {MANIFEST_PATH}",
    )

    try:
        manifest = pd.read_csv(MANIFEST_PATH)
    except Exception as exc:
        add_result(
            results,
            "source_manifest.csv",
            "manifest_required_columns",
            False,
            f"Could not read manifest: {exc}",
        )
        write_reports(results)
        return results

    missing_manifest_columns = sorted(REQUIRED_COLUMNS - set(manifest.columns))
    add_result(
        results,
        "source_manifest.csv",
        "manifest_required_columns",
        not missing_manifest_columns,
        "All required manifest columns are present."
        if not missing_manifest_columns
        else f"Missing manifest columns: {missing_manifest_columns}",
    )

    if missing_manifest_columns:
        write_reports(results)
        return results

    for _, row in manifest.iterrows():
        raw_file_name = str(row["raw_file_name"]).strip()
        raw_path = RAW_DIR / raw_file_name
        expected_columns = parse_expected_columns(row["expected_columns"])

        if not raw_path.exists():
            add_result(
                results,
                raw_file_name,
                "raw_file_exists",
                False,
                f"Raw file not found: {raw_path}",
            )
            continue

        add_result(results, raw_file_name, "raw_file_exists", True, f"Found raw file: {raw_path}")

        try:
            raw_df = pd.read_csv(raw_path)
        except Exception as exc:
            add_result(
                results,
                raw_file_name,
                "raw_file_readable",
                False,
                f"Could not read CSV: {exc}",
            )
            continue

        add_result(
            results,
            raw_file_name,
            "raw_file_readable",
            True,
            f"Rows: {len(raw_df)}, Columns: {len(raw_df.columns)}",
        )

        add_result(
            results,
            raw_file_name,
            "raw_file_non_empty",
            not raw_df.empty,
            f"Rows: {len(raw_df)}",
        )

        actual_columns = {str(column).strip() for column in raw_df.columns}
        missing_expected_columns = sorted(set(expected_columns) - actual_columns)
        add_result(
            results,
            raw_file_name,
            "expected_columns_present",
            not missing_expected_columns,
            "All expected columns are present."
            if not missing_expected_columns
            else f"Missing expected columns: {missing_expected_columns}",
        )

    write_reports(results)
    return results


def main() -> None:
    results = validate_sources()
    failures = [result for result in results if result["status"] == "FAIL"]

    if failures:
        print("Source validation failed.")
        raise SystemExit(1)

    print("Source validation passed.")


if __name__ == "__main__":
    main()
